name: Build (MacOS)
on: workflow_dispatch

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Resolve submodules
        run: git submodule update --init --recursive --depth=1

      - name: Install cmake and curl
        run: | 
          brew update
          brew install --formula cmake curl

      - name: Build with cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S $PWD -B $GITHUB_WORKSPACE/build
          make --directory $GITHUB_WORKSPACE/build

      - name: Upload atrifact
        uses: actions/upload-artifact@v4
        with:
          name: "mytechclinic_chatbot"
          path: "$GITHUB_WORKSPACE/build/mytechclinic_chatbot"
